name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.17.1'

    - name: Change working directory to simple-react-login
      run: cd simple-react-login

    - name: Install dependencies
      run: npm install
      working-directory: ./simple-react-login

    - name: Build the application
      run: npm run build
      working-directory: ./simple-react-login

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./simple-react-login/build
        force_orphan: true   # Forces a clean slate on the gh-pages branch
        keep_files: false    # Ensures that no old files are kept on the gh-pages branch
